FROM python:3.12-slim

WORKDIR /app

COPY Frontend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY Frontend/ .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]